"use client";

type AudioPlayerProps = {
  audioUrl?: string | null;
};

export default function AudioPlayer({
  audioUrl,
}: AudioPlayerProps) {
  return (
    <div
      style={{
        background: "#ffffff",
        marginTop: "25px",
        padding: "24px",
        borderRadius: "12px",
        boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
      }}
    >
      <h2>AI Voice Response</h2>

      <p style={{ margin: "15px 0" }}>
        Listen to the healthcare response generated by HealthTalk AI.
      </p>

      {audioUrl ? (
        <audio controls style={{ width: "100%" }}>
          <source src={audioUrl} type="audio/mpeg" />
          Your browser does not support audio playback.
        </audio>
      ) : (
        <div
          style={{
            padding: "15px",
            borderRadius: "8px",
            backgroundColor: "#f8fafc",
            color: "#64748b",
          }}
        >
          Voice response will appear here after processing.
        </div>
      )}
    </div>
  );
}
